version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    env_file:
      - docker.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - pismonet

  pismo:
    container_name: pismo
    build:
      context: .
    ports:
      - '9001:9001'
    env_file:
      - docker.env
    networks:
      - pismonet
    depends_on:
      postgres:
        condition: service_healthy

networks:
  pismonet:
    driver: bridge

volumes:
  postgresdata:
    driver: local